### ISSUE TITLE
whatwedo/icinga2 - not working

### ISSUE THREAD

**Issue by Rohlik** [whatwedo/docker-base-images#1]
Hi,
your latest image of whatwedo/icinga2 don't work.
I using latest official Mysql Docker image and in Icinga's container logs I can see this error:
`[2016-07-15 13:09:28 +0200] critical/IdoMysqlConnection: Error "Incorrect datetime value: '0000-00-00 00:00:00' for column 'disconnect_time' at row 1" when executing query "INSERT INTO icinga_conninfo (instance_id, connect_time, last_checkin_time, agent_name, agent_version, connect_type, data_start_time) VALUES (1, NOW(), NOW(), 'icinga2 db_ido_mysql', 'r2.4.7-1', 'INITIAL', NOW())"`

And another problem is verify my token in web UI which is generated in container startup.
When I click to "Next" button, this happens:
`Cannot validate token: /etc/icingaweb2/setup.token (FileObject::__construct(/etc/icingaweb2/setup.token): failed to open stream: Permission denied)`

**Comment by n3r0-ch** [comment]
Hi Thomas

The MySQL error is caused by a known Icinga <-> MySQL server version combination (https://dev.icinga.org/issues/10502). You can either reconfigure official MySQL Docker image or use the whatwedo/mariadb image which works without any problems.

The token error is fixed. The new build is currently running and the new image version will be available in the next hour.
